package scoutPojo;

/**
 * file generated by pojo.sodhanalibrary.com
 * 
 * file intended to contain info from bluealliance APIV3's /team/{team_key}/events path
 */

public class EventsPojo {
    private String event_type;

    private String lng;

    private String city;

    private String state_prov;

    private String[] division_keys;

    private String end_date;

    private String event_code;

    private String timezone;

    private String playoff_type_string;

    private String name;

    private String year;

    private String gmaps_url;

    private District district;

    private String key;

    private String lat;

    private String playoff_type;

    private String first_event_code;

    private String location_name;

    private String website;

    private String event_type_string;

    private String first_event_id;

    private String short_name;

    private String country;

    private String gmaps_place_id;

    private Webcasts[] webcasts;

    private String address;

    private String parent_event_key;

    private String postal_code;

    private String start_date;

    private String week;

    public String getEvent_type() {
        return event_type;
    }

    public void setEvent_type(String event_type) {
        this.event_type = event_type;
    }

    public String getLng() {
        return lng;
    }

    public void setLng(String lng) {
        this.lng = lng;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState_prov() {
        return state_prov;
    }

    public void setState_prov(String state_prov) {
        this.state_prov = state_prov;
    }

    public String[] getDivision_keys() {
        return division_keys;
    }

    public void setDivision_keys(String[] division_keys) {
        this.division_keys = division_keys;
    }

    public String getEnd_date() {
        return end_date;
    }

    public void setEnd_date(String end_date) {
        this.end_date = end_date;
    }

    public String getEvent_code() {
        return event_code;
    }

    public void setEvent_code(String event_code) {
        this.event_code = event_code;
    }

    public String getTimezone() {
        return timezone;
    }

    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    public String getPlayoff_type_string() {
        return playoff_type_string;
    }

    public void setPlayoff_type_string(String playoff_type_string) {
        this.playoff_type_string = playoff_type_string;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getGmaps_url() {
        return gmaps_url;
    }

    public void setGmaps_url(String gmaps_url) {
        this.gmaps_url = gmaps_url;
    }

    public District getDistrict() {
        return district;
    }

    public void setDistrict(District district) {
        this.district = district;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getLat() {
        return lat;
    }

    public void setLat(String lat) {
        this.lat = lat;
    }

    public String getPlayoff_type() {
        return playoff_type;
    }

    public void setPlayoff_type(String playoff_type) {
        this.playoff_type = playoff_type;
    }

    public String getFirst_event_code() {
        return first_event_code;
    }

    public void setFirst_event_code(String first_event_code) {
        this.first_event_code = first_event_code;
    }

    public String getLocation_name() {
        return location_name;
    }

    public void setLocation_name(String location_name) {
        this.location_name = location_name;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getEvent_type_string() {
        return event_type_string;
    }

    public void setEvent_type_string(String event_type_string) {
        this.event_type_string = event_type_string;
    }

    public String getFirst_event_id() {
        return first_event_id;
    }

    public void setFirst_event_id(String first_event_id) {
        this.first_event_id = first_event_id;
    }

    public String getShort_name() {
        return short_name;
    }

    public void setShort_name(String short_name) {
        this.short_name = short_name;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getGmaps_place_id() {
        return gmaps_place_id;
    }

    public void setGmaps_place_id(String gmaps_place_id) {
        this.gmaps_place_id = gmaps_place_id;
    }

    public Webcasts[] getWebcasts() {
        return webcasts;
    }

    public void setWebcasts(Webcasts[] webcasts) {
        this.webcasts = webcasts;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getParent_event_key() {
        return parent_event_key;
    }

    public void setParent_event_key(String parent_event_key) {
        this.parent_event_key = parent_event_key;
    }

    public String getPostal_code() {
        return postal_code;
    }

    public void setPostal_code(String postal_code) {
        this.postal_code = postal_code;
    }

    public String getStart_date() {
        return start_date;
    }

    public void setStart_date(String start_date) {
        this.start_date = start_date;
    }

    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    @Override
    public String toString() {
        return "ClassPojo [event_type = " + event_type + ", lng = " + lng + ", city = " + city + ", state_prov = "
                + state_prov + ", division_keys = " + division_keys + ", end_date = " + end_date + ", event_code = "
                + event_code + ", timezone = " + timezone + ", playoff_type_string = " + playoff_type_string
                + ", name = " + name + ", year = " + year + ", gmaps_url = " + gmaps_url + ", district = " + district
                + ", key = " + key + ", lat = " + lat + ", playoff_type = " + playoff_type + ", first_event_code = "
                + first_event_code + ", location_name = " + location_name + ", website = " + website
                + ", event_type_string = " + event_type_string + ", first_event_id = " + first_event_id
                + ", short_name = " + short_name + ", country = " + country + ", gmaps_place_id = " + gmaps_place_id
                + ", webcasts = " + webcasts + ", address = " + address + ", parent_event_key = " + parent_event_key
                + ", postal_code = " + postal_code + ", start_date = " + start_date + ", week = " + week + "]";
    }

    class Webcasts {
        private String file;

        private String type;

        private String channel;

        public String getFile() {
            return file;
        }

        public void setFile(String file) {
            this.file = file;
        }

        public String getType() {
            return type;
        }

        public void setType(String type) {
            this.type = type;
        }

        public String getChannel() {
            return channel;
        }

        public void setChannel(String channel) {
            this.channel = channel;
        }

        @Override
        public String toString() {
            return "ClassPojo [file = " + file + ", type = " + type + ", channel = " + channel + "]";
        }
    }

    class District {
        private String display_name;

        private String year;

        private String abbreviation;

        private String key;

        public String getDisplay_name() {
            return display_name;
        }

        public void setDisplay_name(String display_name) {
            this.display_name = display_name;
        }

        public String getYear() {
            return year;
        }

        public void setYear(String year) {
            this.year = year;
        }

        public String getAbbreviation() {
            return abbreviation;
        }

        public void setAbbreviation(String abbreviation) {
            this.abbreviation = abbreviation;
        }

        public String getKey() {
            return key;
        }

        public void setKey(String key) {
            this.key = key;
        }

        @Override
        public String toString() {
            return "ClassPojo [display_name = " + display_name + ", year = " + year + ", abbreviation = " + abbreviation
                    + ", key = " + key + "]";
        }
    }
}