package scoutPojo;

/**
 * file generated by pojo.sodhanalibrary.com.
 * 
 * file intended to contain info from bluealliance APIV3's /team/{team_key}/matches/{year}/simple path.
 */

public class SimpleMatches {
    private String match_number;

    private String time;

    private String predicted_time;

    private String actual_time;

    private String set_number;

    private String comp_level;

    private Alliances alliances;

    private String winning_alliance;

    private String key;

    private String event_key;

    public String getMatch_number() {
        return match_number;
    }

    public void setMatch_number(String match_number) {
        this.match_number = match_number;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getPredicted_time() {
        return predicted_time;
    }

    public void setPredicted_time(String predicted_time) {
        this.predicted_time = predicted_time;
    }

    public String getActual_time() {
        return actual_time;
    }

    public void setActual_time(String actual_time) {
        this.actual_time = actual_time;
    }

    public String getSet_number() {
        return set_number;
    }

    public void setSet_number(String set_number) {
        this.set_number = set_number;
    }

    public String getComp_level() {
        return comp_level;
    }

    public void setComp_level(String comp_level) {
        this.comp_level = comp_level;
    }

    public Alliances getAlliances() {
        return alliances;
    }

    public void setAlliances(Alliances alliances) {
        this.alliances = alliances;
    }

    public String getWinning_alliance() {
        return winning_alliance;
    }

    public void setWinning_alliance(String winning_alliance) {
        this.winning_alliance = winning_alliance;
    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getEvent_key() {
        return event_key;
    }

    public void setEvent_key(String event_key) {
        this.event_key = event_key;
    }

    @Override
    public String toString() {
        return "ClassPojo [match_number = " + match_number + ", time = " + time + ", predicted_time = " + predicted_time
                + ", actual_time = " + actual_time + ", set_number = " + set_number + ", comp_level = " + comp_level
                + ", alliances = " + alliances + ", winning_alliance = " + winning_alliance + ", key = " + key
                + ", event_key = " + event_key + "]";
    }

    class Alliances {
        private Red red;

        private Blue blue;

        public Red getRed() {
            return red;
        }

        public void setRed(Red red) {
            this.red = red;
        }

        public Blue getBlue() {
            return blue;
        }

        public void setBlue(Blue blue) {
            this.blue = blue;
        }

        @Override
        public String toString() {
            return "ClassPojo [red = " + red + ", blue = " + blue + "]";
        }
    }

    class Red {
        private String[] dq_team_keys;

        private String[] surrogate_team_keys;

        private String score;

        private String[] team_keys;

        public String[] getDq_team_keys() {
            return dq_team_keys;
        }

        public void setDq_team_keys(String[] dq_team_keys) {
            this.dq_team_keys = dq_team_keys;
        }

        public String[] getSurrogate_team_keys() {
            return surrogate_team_keys;
        }

        public void setSurrogate_team_keys(String[] surrogate_team_keys) {
            this.surrogate_team_keys = surrogate_team_keys;
        }

        public String getScore() {
            return score;
        }

        public void setScore(String score) {
            this.score = score;
        }

        public String[] getTeam_keys() {
            return team_keys;
        }

        public void setTeam_keys(String[] team_keys) {
            this.team_keys = team_keys;
        }

        @Override
        public String toString() {
            return "ClassPojo [dq_team_keys = " + dq_team_keys + ", surrogate_team_keys = " + surrogate_team_keys
                    + ", score = " + score + ", team_keys = " + team_keys + "]";
        }
    }

    class Blue {
        private String[] dq_team_keys;

        private String[] surrogate_team_keys;

        private String score;

        private String[] team_keys;

        public String[] getDq_team_keys() {
            return dq_team_keys;
        }

        public void setDq_team_keys(String[] dq_team_keys) {
            this.dq_team_keys = dq_team_keys;
        }

        public String[] getSurrogate_team_keys() {
            return surrogate_team_keys;
        }

        public void setSurrogate_team_keys(String[] surrogate_team_keys) {
            this.surrogate_team_keys = surrogate_team_keys;
        }

        public String getScore() {
            return score;
        }

        public void setScore(String score) {
            this.score = score;
        }

        public String[] getTeam_keys() {
            return team_keys;
        }

        public void setTeam_keys(String[] team_keys) {
            this.team_keys = team_keys;
        }

        @Override
        public String toString() {
            return "ClassPojo [dq_team_keys = " + dq_team_keys + ", surrogate_team_keys = " + surrogate_team_keys
                    + ", score = " + score + ", team_keys = " + team_keys + "]";
        }
    }
}