package scoutPojo;

/**
 * file generated by pojo.sodhanalibrary.com
 * 
 * file intended to contain info from bluealliance APIV3's /status path
 */

public class StatusPojo
{
    private String[] down_events;

    private String current_season;

    private Android android;

    private Ios ios;

    private Web web;

    private String is_datafeed_down;

    private String max_season;

    private String contbuild_enabled;

    public String[] getDown_events ()
    {
        return down_events;
    }

    public void setDown_events (String[] down_events)
    {
        this.down_events = down_events;
    }

    public String getCurrent_season ()
    {
        return current_season;
    }

    public void setCurrent_season (String current_season)
    {
        this.current_season = current_season;
    }

    public Android getAndroid ()
    {
        return android;
    }

    public void setAndroid (Android android)
    {
        this.android = android;
    }

    public Ios getIos ()
    {
        return ios;
    }

    public void setIos (Ios ios)
    {
        this.ios = ios;
    }

    public Web getWeb ()
    {
        return web;
    }

    public void setWeb (Web web)
    {
        this.web = web;
    }

    public String getIs_datafeed_down ()
    {
        return is_datafeed_down;
    }

    public void setIs_datafeed_down (String is_datafeed_down)
    {
        this.is_datafeed_down = is_datafeed_down;
    }

    public String getMax_season ()
    {
        return max_season;
    }

    public void setMax_season (String max_season)
    {
        this.max_season = max_season;
    }

    public String getContbuild_enabled ()
    {
        return contbuild_enabled;
    }

    public void setContbuild_enabled (String contbuild_enabled)
    {
        this.contbuild_enabled = contbuild_enabled;
    }

    @Override
    public String toString()
    {
        return "ClassPojo [down_events = "+down_events+", current_season = "+current_season+", android = "+android+", ios = "+ios+", web = "+web+", is_datafeed_down = "+is_datafeed_down+", max_season = "+max_season+", contbuild_enabled = "+contbuild_enabled+"]";
    }

    class Web {
        private String current_commit;
    
        private String travis_job;
    
        private String commit_time;
    
        private String deploy_time;
    
        public String getCurrent_commit ()
        {
            return current_commit;
        }
    
        public void setCurrent_commit (String current_commit)
        {
            this.current_commit = current_commit;
        }
    
        public String getTravis_job ()
        {
            return travis_job;
        }
    
        public void setTravis_job (String travis_job)
        {
            this.travis_job = travis_job;
        }
    
        public String getCommit_time ()
        {
            return commit_time;
        }
    
        public void setCommit_time (String commit_time)
        {
            this.commit_time = commit_time;
        }
    
        public String getDeploy_time ()
        {
            return deploy_time;
        }
    
        public void setDeploy_time (String deploy_time)
        {
            this.deploy_time = deploy_time;
        }
    
        @Override
        public String toString()
        {
            return "ClassPojo [current_commit = "+current_commit+", travis_job = "+travis_job+", commit_time = "+commit_time+", deploy_time = "+deploy_time+"]";
        }
    }

    class Ios
{
    private String min_app_version;

    private String latest_app_version;

    public String getMin_app_version ()
    {
        return min_app_version;
    }

    public void setMin_app_version (String min_app_version)
    {
        this.min_app_version = min_app_version;
    }

    public String getLatest_app_version ()
    {
        return latest_app_version;
    }

    public void setLatest_app_version (String latest_app_version)
    {
        this.latest_app_version = latest_app_version;
    }

    @Override
    public String toString()
    {
        return "ClassPojo [min_app_version = "+min_app_version+", latest_app_version = "+latest_app_version+"]";
    }
}

class Android
{
    private String min_app_version;

    private String latest_app_version;

    public String getMin_app_version ()
    {
        return min_app_version;
    }

    public void setMin_app_version (String min_app_version)
    {
        this.min_app_version = min_app_version;
    }

    public String getLatest_app_version ()
    {
        return latest_app_version;
    }

    public void setLatest_app_version (String latest_app_version)
    {
        this.latest_app_version = latest_app_version;
    }

    @Override
    public String toString()
    {
        return "ClassPojo [min_app_version = "+min_app_version+", latest_app_version = "+latest_app_version+"]";
    }
}

}