package scoutPojo;

/**
 * file generated by pojo.sodhanalibrary.com
 * 
 * file intended to contain info from bluealliance APIV3's /team/{team_key} path
 */

public class TeamPojo
{
    private String location_name;

    private String website;

    private String nickname;

    private String home_championship;

    private String lng;

    private String rookie_year;

    private String city;

    private String country;

    private String state_prov;

    private String gmaps_place_id;

    private String team_number;

    private String address;

    private String name;

    private String postal_code;

    private String gmaps_url;

    private String motto;

    private String key;

    private String lat;

    public String getLocation_name ()
    {
        return location_name;
    }

    public void setLocation_name (String location_name)
    {
        this.location_name = location_name;
    }

    public String getWebsite ()
    {
        return website;
    }

    public void setWebsite (String website)
    {
        this.website = website;
    }

    public String getNickname ()
    {
        return nickname;
    }

    public void setNickname (String nickname)
    {
        this.nickname = nickname;
    }

    public String getHome_championship ()
    {
        return home_championship;
    }

    public void setHome_championship (String home_championship)
    {
        this.home_championship = home_championship;
    }

    public String getLng ()
    {
        return lng;
    }

    public void setLng (String lng)
    {
        this.lng = lng;
    }

    public String getRookie_year ()
    {
        return rookie_year;
    }

    public void setRookie_year (String rookie_year)
    {
        this.rookie_year = rookie_year;
    }

    public String getCity ()
    {
        return city;
    }

    public void setCity (String city)
    {
        this.city = city;
    }

    public String getCountry ()
    {
        return country;
    }

    public void setCountry (String country)
    {
        this.country = country;
    }

    public String getState_prov ()
    {
        return state_prov;
    }

    public void setState_prov (String state_prov)
    {
        this.state_prov = state_prov;
    }

    public String getGmaps_place_id ()
    {
        return gmaps_place_id;
    }

    public void setGmaps_place_id (String gmaps_place_id)
    {
        this.gmaps_place_id = gmaps_place_id;
    }

    public String getTeam_number ()
    {
        return team_number;
    }

    public void setTeam_number (String team_number)
    {
        this.team_number = team_number;
    }

    public String getAddress ()
    {
        return address;
    }

    public void setAddress (String address)
    {
        this.address = address;
    }

    public String getName ()
    {
        return name;
    }

    public void setName (String name)
    {
        this.name = name;
    }

    public String getPostal_code ()
    {
        return postal_code;
    }

    public void setPostal_code (String postal_code)
    {
        this.postal_code = postal_code;
    }

    public String getGmaps_url ()
    {
        return gmaps_url;
    }

    public void setGmaps_url (String gmaps_url)
    {
        this.gmaps_url = gmaps_url;
    }

    public String getMotto ()
    {
        return motto;
    }

    public void setMotto (String motto)
    {
        this.motto = motto;
    }

    public String getKey ()
    {
        return key;
    }

    public void setKey (String key)
    {
        this.key = key;
    }

    public String getLat ()
    {
        return lat;
    }

    public void setLat (String lat)
    {
        this.lat = lat;
    }

    @Override
    public String toString()
    {
        return "ClassPojo [location_name = "+location_name+", website = "+website+", nickname = "+nickname+", home_championship = "+home_championship+", lng = "+lng+", rookie_year = "+rookie_year+", city = "+city+", country = "+country+", state_prov = "+state_prov+", gmaps_place_id = "+gmaps_place_id+", team_number = "+team_number+", address = "+address+", name = "+name+", postal_code = "+postal_code+", gmaps_url = "+gmaps_url+", motto = "+motto+", key = "+key+", lat = "+lat+"]";
    }
}